name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: '2.6'
            gemfile: 'rails_5.2'
          - ruby: '2.6'
            gemfile: 'rails_6.0'
          - ruby: '2.6'
            gemfile: 'rails_6.1'
          - ruby: '2.7'
            gemfile: 'rails_6.0'
          - ruby: '2.7'
            gemfile: 'rails_6.1'
          - ruby: '2.7'
            gemfile: 'rails_7.0'
          - ruby: '2.7'
            gemfile: 'rails_7.1'
          - ruby: '3.0'
            gemfile: 'rails_6.1'
          - ruby: '3.0'
            gemfile: 'rails_7.0'
          - ruby: '3.0'
            gemfile: 'rails_7.1'
          - ruby: '3.1'
            gemfile: 'rails_6.1'
          - ruby: '3.1'
            gemfile: 'rails_7.0'
          - ruby: '3.1'
            gemfile: 'rails_7.1'
          - ruby: '3.1'
            gemfile: 'rails_7.2'
          - ruby: '3.2'
            gemfile: 'rails_6.1'
          - ruby: '3.2'
            gemfile: 'rails_7.0'
          - ruby: '3.2'
            gemfile: 'rails_7.1'
          - ruby: '3.2'
            gemfile: 'rails_7.2'
          - ruby: '3.2'
            gemfile: 'rails_8.0'
          - ruby: '3.2'
            gemfile: 'rails_8.1'
          - ruby: '3.3'
            gemfile: 'rails_6.1'
          - ruby: '3.3'
            gemfile: 'rails_7.0'
          - ruby: '3.3'
            gemfile: 'rails_7.1'
          - ruby: '3.3'
            gemfile: 'rails_7.2'
          - ruby: '3.3'
            gemfile: 'rails_8.0'
          - ruby: '3.3'
            gemfile: 'rails_8.1'
          - ruby: '3.4'
            gemfile: 'rails_6.1'
          - ruby: '3.4'
            gemfile: 'rails_7.0'
          - ruby: '3.4'
            gemfile: 'rails_7.1'
          - ruby: '3.4'
            gemfile: 'rails_7.2'
          - ruby: '3.4'
            gemfile: 'rails_8.0'
          - ruby: '3.4'
            gemfile: 'rails_8.1'
          - ruby: '4.0'
            gemfile: 'rails_6.1'
          - ruby: '4.0'
            gemfile: 'rails_7.0'
          - ruby: '4.0'
            gemfile: 'rails_7.1'
          - ruby: '4.0'
            gemfile: 'rails_7.2'
          - ruby: '4.0'
            gemfile: 'rails_8.0'
          - ruby: '4.0'
            gemfile: 'rails_8.1'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
